docs: added README
mpfan/SYSC-3303-Elevator-Simulator pull request #3
Opened 2020-01-20 18:57 UTC by Souheil-Yazji

Let me know if anything else should be added to the README.

#1

2020-01-21 19:50 UTC, ChristopheTran reviewed
Looks good. Just a thought but should we include our group number?

2020-01-21 20:03 UTC, Souheil-Yazji commented
> Looks good. Just a thought but should we include our group number?

done!

2020-01-21 23:33 UTC, dershao requested changes

2020-01-21 23:33 UTC, dershao commented on README.md
> +Use the following link for [commit convetion](https://www.conventionalcommits.org/en/v1.0.0/). All contributions to the project should pretain to an [Issue](https://github.com/mpfan/SYSC-3303-Elevato
Commit Convention vs Commit convetion

2020-01-22 22:51 UTC, Souheil-Yazji commented on README.md
> +Use the following link for [commit convetion](https://www.conventionalcommits.org/en/v1.0.0/). All contributions to the project should pretain to an [Issue](https://github.com/mpfan/SYSC-3303-Elevato
Done!

2020-01-23 01:23 UTC, dershao approved these changes

2020-01-26 01:32 UTC, merged